### PR TITLE
Fix CI issue

### LINKED ISSUE #103: CI Broken
CI failed on the last commit (before my stream of ugly commits trying to diagnose). Looks like it fails on previous commits as well, so I think this is actually an issue with the CI, not the commit.

### PR DESCRIPTION
**Pull request by damccorm**
Right now, npm test is failing in CI for lower versions of node. This is happening because it is trying to build before testing. This fixes this.

Fixes #103

### CODE REVIEW

File: make.js [hunk 1]
```diff
@@ -86,6 +86,20 @@ target.test = function() {
     run('mocha test/tests');
 }
 
+target.testNoBuild = function() {
```
Comment (stephenmichaelf) [inline make.js]: Can we just make test be no build instead of having two?

File: make.js [hunk 2]
```diff
@@ -86,6 +86,20 @@ target.test = function() {
...
+    pushd('test')
+    run('npm install ../_build');
+    popd();
+
+    console.log("-------Unit Tests-------");
+    run('tsc -p ./test/units');
+    run('mocha test/units');
+
+    console.log("-------Other Tests-------");
```
Comment (stephenmichaelf) [inline make.js]: What are "other" tests?

File: package.json [hunk 3]
```diff
@@ -6,6 +6,7 @@
   "scripts": {
     "build": "node make.js build",
     "test": "node make.js test",
+    "testNoBuild": "node make.js testNoBuild",
```
Comment (stephenmichaelf) [inline package.json]: Does the yaml script need to be updated?

File: make.js (hunk 1 above)
Comment (damccorm) [reply make.js]: I could go either way on this. I think its nice to build before testing in general because it removes that step. I updated for better modularity though so its less of a big deal. If you feel strongly I'm also ok getting rid of this

File: make.js (hunk 2 above)
Comment (damccorm) [reply make.js]: Non-nock tests. I don't really know what the best name for them is, the only difference here is that they actually make http calls. They're not really integration tests since they're still only testing individual components, but they also are a little more involved/flaky than the units.

File: package.json (hunk 3 above)
Comment (damccorm) [reply package.json]: I think I did this above

File: make.js (hunk 2 above)
Comment (stephenmichaelf) [reply make.js]: Integration is close enough I think.

File: make.js (hunk 1 above)
Comment (stephenmichaelf) [reply make.js]: Yeah let's get rid of it and keep them separate.

File: make.js (hunk 2 above)
Comment (damccorm) [reply make.js]: Ok, should be good to go

**Comment by stephenmichaelf** [comment]
Is this still broken? Can we merge?

**Comment by damccorm** [comment]
I think yes to both, I'll merge.
